// Generated by CoffeeScript 1.6.2
$(document).ready(function() {
  return $('#reason-tabs li').click(function() {
    var current, id, selected;

    current = $(this).parent().find('.focus');
    selected = $('#reasons').find('.selected');
    id = $(this).attr('id');
    current.removeClass('focus').parent().find('#' + id).addClass('focus');
    return selected.removeClass('selected').parent().find('#' + id + '-text').addClass('selected');
  });
});
